using Xamarin.Forms;
using Xamarin.Forms.Xaml;

[assembly: XamlCompilation(XamlCompilationOptions.Compile)]
[assembly: ExportFont("Montserrat-Black.ttf", Alias = "Montserrat")]
[assembly: ExportFont("Montserrat-BlackItalic.ttf", Alias = "Montserrat")]
[assembly: ExportFont("Montserrat-Bold.ttf", Alias = "Montserrat")]
[assembly: ExportFont("Montserrat-BoldItalic.ttf", Alias = "Montserrat")]
[assembly: ExportFont("Montserrat-ExtraBold.ttf", Alias = "Montserrat")]
[assembly: ExportFont("Montserrat-ExtraBoldItalic.ttf", Alias = "Montserrat")]
[assembly: ExportFont("Montserrat-ExtraLight.ttf", Alias = "Montserrat")]
[assembly: ExportFont("Montserrat-ExtraLightItalic.ttf", Alias = "Montserrat")]
[assembly: ExportFont("Montserrat-Italic.ttf", Alias = "Montserrat")]
[assembly: ExportFont("Montserrat-Light.ttf", Alias = "Montserrat")]
[assembly: ExportFont("Montserrat-LightItalic.ttf", Alias = "Montserrat")]
[assembly: ExportFont("Montserrat-Medium.ttf", Alias = "Montserrat")]
[assembly: ExportFont("Montserrat-MediumItalic.ttf", Alias = "Montserrat")]
[assembly: ExportFont("Montserrat-Regular.ttf", Alias = "Montserrat")]
[assembly: ExportFont("Montserrat-SemiBold.ttf", Alias = "Montserrat")]
[assembly: ExportFont("Montserrat-SemiBoldItalic.ttf", Alias = "Montserrat")]
[assembly: ExportFont("Montserrat-Thin.ttf", Alias = "Montserrat")]
[assembly: ExportFont("Montserrat-ThinItalic.ttf", Alias = "Montserrat")]